name: DispenserFill
main: me.trickster489.dispenserfill.DispenserFill
version: 1.0
author: Trickster489
commands:
  fill:
    description: Fill nearby dispensers with the item in your hand.
permissions:
  dispenserfill.fill:
    description: Access to the /fill command.